# Generated by Django 6.0.3 on 2026-03-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
    ]
